version: '2'
services:
  web:
    image: mhart/alpine-node:6
    volumes:
      - '.:/fraggle-rock'
    ports:
      - '80:9999'
    env_file:
      .env
    command: node fraggle-rock/server/app.js
  socket1:
    image: mhart/alpine-node:6
    volumes:
      - '.:/fraggle-rock'
    ports:
      - '3001:3001'
    command: node fraggle-rock/socket/app.js
  socket2:
    image: mhart/alpine-node:6
    volumes:
      - '.:/fraggle-rock'
    ports:
      - '3002:3001'
    command: node fraggle-rock/socket/app.js
