version: '2'
services:
  web:
    image: mhart/alpine-node:6
    volumes:
      - '.:/fraggle-rock'
    ports:
      - '80:9999'
    command: node fraggle-rock/server/app.js
  socket:
    image: mhart/alpine-node:6
    volumes:
      - '.:/fraggle-rock'
    ports:
      - '3333:3333'
      - '3332:3332'
    command: node fraggle-rock/socket/app.js