version: '2'
services:
  web:
    image: nicklathen/sbb
    ports:
      - '9999:9999'
    command: node fraggle-rock/server/app.js
  socket:
    image: nicklathen/sbb
    ports:
      - '3333:3333'
      - '3332:3332'
    command: node fraggle-rock/socket/app.js