version: '2'
services:
  web:
    image: mhart/alpine-node:6
    volumes:
      - '.:/fraggle-rock'
    ports:
      - '80:9999'
    env_file:
      .env
    command: node fraggle-rock/server/app.js
  socketmanager:
    image: mhart/alpine-node:6
    volumes:
      - '.:/fraggle-rock'
    ports:
      - '4444:4444'
    env_file:
      .env
    command: node fraggle-rock/socket/socketManager.js